$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  trimming:
    type: object
    properties:
      skip:
        type: boolean
      adapter:
        type: string
        pattern: "^[ACGT]+$"

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  pca:
    type: object
    properties:
      color:
        type: string
      fill:
        type: string
      labels:
        type: string
    required:
      - color
      - fill
      - labels

  diffexp:
    type: object
    properties:
      contrasts:
        type: object
      organism:
        type: string
      collapse:
        type: boolean
    required:
      - contrasts
      - organism

  params:
    type: object
    properties:
      star:
        type: string
      cutadapt-se:
        type: string
      cutadapt-pe:
        type: string
      batch_adjust:
        type: string
      enrichement:
        type: boolean
    required:
      - star
      - cutadapt-se
      - cutadapt-pe
      - batch_adjust

required:
  - samples
  - trimming
  - ref
  - pca
  - diffexp
  - params
